export const IpcChannels = {
  listInterfaces: 'network:list-interfaces',
  pingInterfaces: 'network:ping-interfaces',
  deviceBindingSupported: 'network:device-binding-supported',
  openNetworkSettings: 'network:open-settings',
  setNetworkPreference: 'network:set-preference',
  getThemeSource: 'theme:get-source',
  setThemeSource: 'theme:set-source',
  setStreamsPerNetwork: 'streams:set-per-network',
  probeUrl: 'download:probe',
  getInitialState: 'app:get-initial-state',
  setDestinationDir: 'destination:set-dir',
  chooseDestinationFolder: 'dialog:choose-destination-folder',
  chooseSourceFile: 'dialog:choose-source-file',
  readClipboardText: 'clipboard:read-text',
  revealInFolder: 'shell:reveal-in-folder',
  startDownload: 'download:start',
  startSimulatedDownload: 'download:start-simulated',
  getCurrentDownload: 'download:get-current',
  pauseDownload: 'download:pause',
  resumeDownload: 'download:resume',
  cancelDownload: 'download:cancel',
  removeDownload: 'download:remove',
  downloadUpdated: 'download:updated',
  toggleDevToolsPanel: 'dev:toggle-panel',
  checkForUpdate: 'update:check',
  dismissUpdate: 'update:dismiss'
} as const
