export const IpcChannels = {
  listInterfaces: 'network:list-interfaces',
  pingInterfaces: 'network:ping-interfaces',
  deviceBindingSupported: 'network:device-binding-supported',
  openNetworkSettings: 'network:open-settings',
  probeUrl: 'download:probe',
  getInitialState: 'app:get-initial-state',
  updateSettings: 'app:update-settings',
  chooseDestinationFolder: 'dialog:choose-destination-folder',
  chooseSourceFile: 'dialog:choose-source-file',
  readClipboardText: 'clipboard:read-text',
  revealInFolder: 'shell:reveal-in-folder',
  startDownload: 'download:start',
  getCurrentDownload: 'download:get-current',
  pauseDownload: 'download:pause',
  resumeDownload: 'download:resume',
  cancelDownload: 'download:cancel',
  removeDownload: 'download:remove',
  downloadUpdated: 'download:updated',
  checkForUpdate: 'update:check'
} as const
